# Generated by Django 5.2.8 on 2026-01-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_alter_rubric_options_rubric_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Цена'),
        ),
    ]
