# Generated by Django 5.2.8 on 2026-02-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
