"""
Django settings for samplesite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-h%hc0u$tg&nes(!hs&o+*lu=(4^aq*+$7b$jt+*^af-#6e#1b-'
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'captcha',
    'precise_bbcode',
    'django_bootstrap5',
    'rest_framework',
    'corsheaders',

    'bboard',
    'testapp',

    'easy_thumbnails',
    'django_cleanup',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'django.middleware.cache.UpdateCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'bboard.middleware.RubricMiddleware',
]

ROOT_URLCONF = 'samplesite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bboard.middleware.rubrics',
            ],
            # 'libraries': {
            #     'bbtags': 'bboard.templatetags.bbtags',
            # },
            # 'builtins': [
            #     'bboard.templatetags.bbtags',
            # ],
        },
    },
]

WSGI_APPLICATION = 'samplesite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # 'ATOMIC_REQUEST': False,
        # 'AUTOCOMMIT': True,
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": "postgres",
#         "USER": "postgres",
#         "PASSWORD": "1234",
#         "HOST": "127.0.0.1",
#         "PORT": "5433",
#     }
# }
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": env('NAME'),
#         "USER": env('USER'),
#         "PASSWORD": env('PASSWORD'),
#         "HOST": "127.0.0.1",
#         "PORT": "5433",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {'max_similarity': 0.7},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'testapp.models.AdvUser'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True

DEFAULT_CHARSET = 'utf-8'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = '/'

# CAPTCHA
CAPTCHA_LENGTH = 8
CAPTCHA_BACKGROUND_COLOR = "#ff0000"
CAPTCHA_FOREGROUND_COLOR = "#ff00ff"
CAPTCHA_LETTER_ROTATION = (-180, 180)
CAPTCHA_FONT_SIZE = 58
CAPTCHA_IMAGE_SIZE = (600, 250)

# precise_bbcode
BBCODE_NEWLINE = '<br>'
BBCODE_SMILIES_UPLOAD_TO = BASE_DIR / 'static/precise_bbcode/smilies'

# FILE_UPLOAD_MAX_MEMORY_SIZE = 2_621_440


# easy-thumbnail
THUMBNAIL_ALIASES = {
    'bboard.Bb.picture': {
        'default': {
            'size': (500, 300),
            'crop': 'scale',
        },
    },
    'testapp': {
        'default': {
            'size': (400, 300),
            'crop': 'smart',
            'bw': True,
        },
    },
    '': {
        'default': {
            'size': (180, 240),
            'crop': 'scale',
        },
        'big': {
            'size': (480, 640),
            'crop': '10,10',
        },
    },
}

THUMBNAIL_DEFAULT_OPTIONS = {
    'quality': 90,
    'subsampling': 1,
}

THUMBNAIL_MEDIA_ROOT =  ''
THUMBNAIL_MEDIA_URL = '/thumbs/'
THUMBNAIL_BASEDIR = 'thumbs'


# SESSIONS
# SESSION_ENGINE = "django.contrib.sessions.backends.db"  # по умолчанию
# SESSION_ENGINE = "django.contrib.sessions.backends.file"
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_ENGINE = "django.contrib.sessions.backends.cache_db"
# SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

# MESSAGES
# MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
# MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
# MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'  # по умолчанию

# from django.contrib import messages
# MESSAGE_LEVEL = 20
# MESSAGE_LEVEL = messages.DEBUG

# EMAIL
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = 'localhost'  # по умолчанию
# EMAIL_PORT = 25
# EMAIL_HOST_USER = ''  # имя пользователя
# EMAIL_HOST_PASSWORD = ''  # пароль
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = False
# EMAIL_SSL_CERTFILE = None
# EMAIL_SSL_KEYFILE = None
# EMAIL_TIMEOUT = None

EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / 'email'

# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
# EMAIL_BACKEND = "django.core.mail.backends.dummy.EmailBackend"

DEFAULT_FROM_EMAIL = 'webmaster@localhost'  # по умолчанию

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
#         # 'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#         # 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         # 'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',  # Удалён
#         # 'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
#
#         'LOCATION': 'cache1',
#         'TIMEOUT': 60,
#         'OPTIONS': {
#             'MAX_ENTRIES': 200,
#         },
#         # 'VERSION': 1,
#     },
#     # 'special': {
#     #     'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#     #
#     #     'LOCATION': 'cache2',
#     # }
# }

# CACHE_MIDDLEWARE_SECONDS = 1


### DRF (CORS) ###
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOWED_ORIGINS = [
#     'http://www.bboard.kz',
#     'https://www.bboard.kz',
# ]
# CORS_ALLOW_METHODS = [
#     'GET',
#     'POST',
# ]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    )
}
