# Generated by Django 5.2.8 on 2026-01-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
